config/routes.rb
ETFlex::Application.routes.draw do

  resources :scenes, except: %w( new create edit update destroy ) do
    get  'with/:id', to: 'scenarios#show', as: :scenario
    post 'with/:id', to: 'scenarios#update'
    put  'with/:id', to: 'scenarios#update'

    member { get 'fresh' }
  end

  # High scoring scenarios for the high scores list.
  get 'scenes/:scene_id/scenarios/since/:days', to: 'scenarios#since'

  # Devise -------------------------------------------------------------------

  devise_for :users

  devise_scope :user do
    get '/hello',   to: 'devise/sessions#new'
    get '/goodbye', to: 'devise/sessions#destroy'
  end

  # Update username via JSON.
  put '/me', to: 'pages#update_username'

  # Backstage and Administration ---------------------------------------------

  namespace :backstage do
    resources :scenes do
      resources :props,  controller: 'scene_props',  except: :show
    end

    get '/', to: redirect('/backstage/scenes')
  end

  # Default Path -------------------------------------------------------------

  # A temporary page for viewing / testing what will become the root page.
  get '/lang/:locale', to: 'pages#lang'

  get '/supported_browsers', to: 'pages#supported_browsers'

  root to: 'pages#root'

end

app/views/pages/_browser_warning.html.haml
%aside#browser_warning
  %h2
    = t 'browser_warning'
    = link_to "#{ h(t("more_info")) }&hellip;".html_safe, supported_browsers_path

app/views/pages/_landing_en.html.haml
%p
  Can you create a clean energy future for 2030 and keep the lights
  from going out when there is no wind or sunshine? Can you reduce 
  greenhouse gas emissions and keep global warming in check?
  Can you do all that at the lowest possible costs? Can you get 
  high-score by building the brightest future of all? Get live 
  updates of other people's scores and share your vision with others
  on Facebook or Twitter. 
  
%p
  This game is based on real energy data and was created by 
  Quintel Intelligence together with almost all parties (corporate, 
  government and education) involved in energy in the Netherlands.
  When you are done playing at this level, perhaps it is time to move
  on to the real thing and build an energy future using the 
  professional version of the Energy Transition Model.

app/views/pages/_landing_nl.html.haml
%p 
  Kun je een schone energietoekomst bouwen voor 2030 zonder dat het
  licht uitgaat als de zon niet schijnt en de wind niet waait? Kun je
  zorgen dat de aarde minder opwarmt door het terugdringen van de
  CO<sub>2</sub> uitstoot? En dat allemaal tegen de laagst mogelijke
  prijs? Kun jij de toekomst zo mooi bouwen dat je ook de hoogste score
  haalt? Zie real-time wat anderen aan score halen en deel je 
  toekomstvisie met je vrienden op Facebook, Twitter.

%p 
  Dit spel is gebaseerd op de echte energiedata van Nederland en is
  gemaakt door Quintel Intelligence in samenwerking met praktisch alle 
  partijen (bedrijven, overheid en onderwijs) die in Nederland met 
  energie bezig zijn. Als je uitgespeeld bent op het eerste
  niveau van het spel kun je door naar het echte werk en een
  energietoekomst bouwen met de professionele versie van het 
  Energietransitiemodel.

app/views/pages/_scene.html.haml
- latest_scenario = scenarios_for_current_user(scene).all.first

.scene[ scene ]
  %h2
    = link_to scene.name, scene

  %p.description
    Try to balance the demand for energy in your country with the costs of
    building new power stations, and the need for clean renewable energy.

  - if latest_scenario.present?
    %p.scene-actions
      = link_to 'Resume', scene_scenario_url(scene, latest_scenario)
      = link_to 'Start Over', scene_url(scene)
  - else
    %p.scene-actions
      = link_to 'Try the Challenge&hellip;'.html_safe, scene_url(scene)

  .scenarios
    .your-scenarios.scenario-list
      %ul
        - scenarios_for_current_user(scene).each do |scenario|
          %li
            %a(href="#{ scene_scenario_url(scene, scenario) }")
              .score= scenario_score scenario
              .info= scenario_age scenario

    .others-scenarios.scenario-list
      %ul
        - scenarios_for_other_users(scene).each do |scenario|
          %li
            %a(href="#{scene_scenario_url(scene, scenario)}")
              .score= scenario_score scenario
              .info
                %span.author= scenario_owner scenario
                %span.time= scenario_age scenario

app/views/pages/_theme_header.html.haml
- @icon_props = { car:                 %w[suv eco],
                  city:                %w[medium small large],
                  eco_buildings:       %w[green coal_dry],
                  energy_sources:      %w[solar nuclear oil],
                  geothermal_pipeline: %w[none geothermal pipeline],
                  ground:              %w[green dry],
                  solar_heater:        %w[none heater],
                  turbines:            %w[wind coal] }

#theme-header
  %a#logo(href="/") Energy Transition Model light
  .world{"data-prop-location" => "header"}
    .plane
    .sun
    - @icon_props.each do |key, states|
      .icon-prop{class: key.to_s.gsub(/_/,"-")}
        - active_state = states.first
        - states.each do |state|
          %span.icon{ class: "#{state.gsub(/_/,'-')} #{active_state == state ? 'active' : 'inactive'}",
                      style: ("display: none;" unless active_state == state ) }

app/views/pages/root.html.haml
- # DEBT: Move this definition to controller...

- unless supported_browser?
  = render 'browser_warning'

#page-view.root
  #core
    = link_to 'Energy Transition Model', root_path, id: 'logo'
    %nav#language-select
      - @alternative_locales.each do |alt_locale|
        %a{href: "/lang/#{alt_locale}", title: (t :'switch_to_this_language', locale: alt_locale), class: alt_locale}
          = t :'switch_to_this_language', locale: alt_locale

    -# = render 'theme_header'

    %section#main

      %h1
        = t(:'scenes.etlite.landingTitle', future: t(:'scenes.etlite.landingFuture')).html_safe
        %em= t :'scenes.etlite.landingSubtitle'

      = render partial: "landing_#{ I18n.locale }"

      - @scenes.each do |scene|
        - previous_attempt = scene.previous_attempt(current_or_guest_user)
        .level
          %h2= t("scenes.#{scene.name_key}")

          = link_to(image_tag("scenes/#{scene.name_key}/impression.jpg", height: '350px'), create_or_continue_playing_path(scene), class: 'poster')

          %section.go
            - if ETFlex.config.conference and previous_attempt
              %span.buttons
                %a.blue.launch{ href: "/scenes/#{scene.id}/fresh" }<>
                  == #{ t :'scenes.etlite.landingButton' }&hellip;

              .conference-continue
                == #{ t :'words.or' }:

                %a{ href: scene_scenario_path(scene_id: scene, id: previous_attempt) }
                  == #{ t :'scenes.etlite.backToPrevious' }&hellip;

            - elsif scene.previous_attempt(current_or_guest_user)
              %span.buttons
                %a.blue.launch{ href: scene_scenario_path(scene_id: scene, id: previous_attempt) }<>
                  == #{ t :'scenes.etlite.continue' }&hellip;

              .start-over
                == #{ t :'words.or' }:
                %a{ href: "/scenes/#{scene.id}" }== #{ t :'scenes.etlite.startOver' }&hellip;

            - else

              %span.buttons
                %a.blue.launch{ href: scene_path(scene) }<>
                  == #{ t :'scenes.etlite.landingButton' }&hellip;

                .start-over &nbsp;


          - if scores_enabled?
            #scores.scores.condensed{ data: {scene: scene.id} }
              %h2== #{ t :'words.high_scores' }:
              .loading== #{ t :'words.loading' }&hellip;

    %footer
      %ul#partners
        %li
          %a{href: "http://www.gasterra.nl", "data-navigate" => "noclient", class:"partner gasterra"} GasTerra
        %li.by= t :'leading_partner'

:javascript
  window.bootstrap = #{ high_scores_pusher_event(@high_scenarios).to_json }

app/views/pages/supported_browsers.html.haml
!!! 5
%html
  %head
    %title= I18n.t "etm_light"
    = stylesheet_link_tag 'application'

  %body
    #page-view.root
      #core
        = render 'theme_header'

        %section#main

          %h1 Why your browser is not (fully) supported...

          %p
            The ETM is a modern web application that tries to be available on as many
            browsers as possible.

            Currently we support the following browsers and devices:

          %ul
            = raw ETFlex.config.supported_browsers.sort.map{ |b| "<li>#{ b.humanize }</li>" }.join

          %p
            If you encounter a bug on your browser, you can help us improve the
            ETM-light by sending us the name of your browser with a description
            (or screenshot) of what went wrong to:
            <a href="mailto:etm@quintel.com">etflex@quintel.com</a>.

          %p
            Thank you very much, Quintel Intelligence